### ISSUE TITLE
Test Suite fails on Node 14.x

### ISSUE THREAD

**Issue by ligerzero459** [ligerzero459/wait-for-url#2]
On Node 14.x, test suite fails due to a change that occured in the Node HTTP module. Error is:
```  
test: TAP
  at:
    line: 643
    column: 15
    file: _http_outgoing.js
    function: writeAfterEnd
  stack: |
    Server.<anonymous> (test/wait_for_url.js:44:7)
  code: ERR_STREAM_WRITE_AFTER_END
  tapCaught: uncaughtException
```

Need to diagnose the root cause and fix it so package is actually supported by Node 14 officially
